version: "3.9"

name: helmes_homework

services:
  db:
    image: postgres:17
    container_name: helmes_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helmes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d helmes"]
      interval: 5s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: helmes_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/helmes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: helmes_frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:8080/api
    depends_on:
      - backend

volumes:
  postgres_data:
